Development
q2g/q2g-helper-qlik-nuget pull request #2
Opened 2019-03-04 11:58 UTC by mossbeard

Is code ok, please create a nuget

2019-03-04 14:53 UTC, konne requested changes
@mossbeard please see comments

2019-03-04 14:53 UTC, konne commented on src/Q2gHelperQlik.csproj
> +    <CreateProperty Value="$(GitVersion_InformationalVersion)">
@mossbeard please move this block one block up

2019-03-04 14:53 UTC, konne commented on src/Q2gHelperQlik.csproj
> +  <ItemGroup Condition="'$(TargetFramework)' == 'net452'">
please add an "or" in the condition

2019-03-04 14:53 UTC, konne commented on src/Q2gHelperQlik.csproj
> +  <ItemGroup Condition="'$(TargetFramework)' == 'net452'">
or check $(MyProperty.Substring(0, 4) = net4

2019-03-04 14:53 UTC, konne commented on src/Q2gHelperQlik.csproj
> +  <ItemGroup Condition="'$(TargetFramework)' == 'net452'">
in the build file take one position to combine all check and set a new
for example: <DefineConstants>$(DefineConstants);CLASSICNET;</DefineConstants>
And us this the the code with.
#if CLASSICNET

#endif

2019-03-05 08:30 UTC, mossbeard commented
@konne  
I have chnage the project file now. In this case, I still have old states in the .cs files noticed that I have fixed with the same.

2019-03-05 12:27 UTC, konne approved these changes
@mossbeard please merge

2019-03-05 12:28 UTC, merged